language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo mv nltk_data /usr/share/nltk_data    
# command to run tests
script: 
    - cd streampredictor
    - nosetests
sudo: required
