language: python
python:
  - "3.5"
# command to install dependencies
install:
  # install TensorFlow
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl;
    fi
  - pip install -r requirements.txt
  - sudo mv nltk_data /usr/share/nltk_data    
# command to run tests
script: 
    - cd streampredictor
    - nosetests
sudo: required
